---
title: "p8105_hw2_tw3108"
author: "Tao Wu"
date: "2025-10-01"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message=FALSE,warning=FALSE}
library(tidyverse)
pols <- read_csv("data/pols-month.csv")
snp  <- read_csv("data/snp.csv")
unemp <- read_csv("data/unemployment.csv")
newpols <- pols %>%
  separate(mon, into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    month = as.integer(month),
    month = month.name[month],
    president = if_else(prez_gop == 1, "gop", "dem")
  ) %>%
  select(-prez_gop, -prez_dem, -day)
newsnp <- snp %>%
 mutate(date = as.Date(date, format = "%m/%d/%y"),
    year = as.integer(format(date, "%Y")),
    month = as.integer(format(date, "%m")),
    month = month.name[month]
  ) %>%
  select(year, month, close) %>%    
  arrange(year, month)
newunemp <- unemp %>%
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "rate"
  ) %>%
  mutate(
    year  = as.integer(Year),
    month = month.name[match(month,month.abb)]
  ) %>%
  select(year, month, rate) %>%
  arrange(year,month)
newpols   <- newpols   %>% mutate(year = as.integer(year))
newsnp    <- newsnp    %>% mutate(year = as.integer(year))
newunemp  <- newunemp  %>% mutate(year = as.integer(year))
merged <- newpols %>%
  left_join(newsnp, by = c("year", "month"))
final <- merged %>%
  left_join(newunemp, by = c("year", "month"))
```

```{r,message=FALSE,warning=FALSE}
library(readxl)
library(dplyr)
data <- "data/202409 Trash Wheel Collection Data.xlsx"

mrtrash <- read_excel(
  data,
  sheet = "Mr. Trash Wheel",
  skip  = 1,
  range = readxl::cell_cols("A:M")
) %>%
  filter(!is.na(Dumpster)) %>%
  rename(
    weight_tons         = `Weight (tons)`,
    volume_cubic_yards  = `Volume (cubic yards)`,
    plastic_bottles     = `Plastic Bottles`,
    polystyrene         = Polystyrene,
    cigarette_butts     = `Cigarette Butts`,
    glass_bottles       = `Glass Bottles`,
    plastic_bags        = `Plastic Bags`,
    wrappers            = Wrappers,
    sports_balls        = `Sports Balls`
  ) %>%
  mutate(
    Year           = as.integer(Year),
    Month          = as.character(Month),
    Date           = as.Date(Date),
    weight_tons    = as.numeric(weight_tons),
    cigarette_butts= as.numeric(cigarette_butts),
    sports_balls   = as.integer(round(as.numeric(sports_balls))),
    member         = "Mr.Trash Wheel"
  )

proftrash <- read_excel(
  data,
  sheet = "Professor Trash Wheel",
  skip  = 1,
  range = readxl::cell_cols("A:M")
) %>%
  filter(!is.na(Dumpster)) %>%
  rename(
    weight_tons         = `Weight (tons)`,
    volume_cubic_yards  = `Volume (cubic yards)`,
    plastic_bottles     = `Plastic Bottles`,
    polystyrene         = Polystyrene,
    cigarette_butts     = `Cigarette Butts`,
    glass_bottles       = `Glass Bottles`,
    plastic_bags        = `Plastic Bags`,
    wrappers            = Wrappers
  ) %>%
  mutate(
    Year           = as.integer(Year),
    Month          = as.character(Month),
    Date           = as.Date(Date),
    weight_tons    = as.numeric(weight_tons),
    cigarette_butts= as.numeric(cigarette_butts),
    sports_balls   = NA_integer_, 
    member         = "Professor Trash Wheel"
  )

gwynnda <- read_excel(
  data,
  sheet = "Gwynnda Trash Wheel",
  skip  = 1,
  range = readxl::cell_cols("A:L")
) %>%
  filter(!is.na(Dumpster)) %>%
  rename(
    weight_tons         = `Weight (tons)`,
    volume_cubic_yards  = `Volume (cubic yards)`,
    plastic_bottles     = `Plastic Bottles`,
    polystyrene         = Polystyrene,
    cigarette_butts     = `Cigarette Butts`,
    plastic_bags        = `Plastic Bags`,
    wrappers            = Wrappers
  ) %>%
  mutate(
    Year           = as.integer(Year),
    Month          = tolower(as.character(Month)),
    Date           = as.Date(Date),
    weight_tons    = as.numeric(weight_tons),
    cigarette_butts= as.numeric(cigarette_butts),
    sports_balls   = NA_integer_,   
    member         = "Gwynnda"
  )

trashwheel <- bind_rows(mrtrash, proftrash, gwynnda)
```

```{r,message=FALSE,warning=FALSE}
library(tidyverse)
zori <- readr::read_csv("data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv")
newzori <- zori %>%
  rename(zip = RegionName) %>%
  pivot_longer(
    cols = -(1:9),
    names_to  = "date",
    values_to = "zori"
  ) %>%
  tidyr::separate(
    date, into = c("year","month","day"),
    sep = "-", convert = TRUE
  ) %>%
  mutate(
    date = as.Date(year, month, day),
  ) %>%
  select(zip, date, year, month, zori) %>%
  arrange(zip, date)
zip <- read_csv("data/Zip Codes.csv") %>%
  rename(zip = ZipCode, county= County,neighborhood = Neighborhood
  )
tidy <- newzori %>%
  left_join(zip, by = "zip") %>%
  relocate(zip, county, neighborhood, date, year, month, zori) %>%
  arrange(zip, date)
```
